# Generated by Django 6.0.2 on 2026-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="payment ID"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии"),
        ),
    ]
