# Generated by Django 6.0.2 on 2026-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments_checkout_url_payments_stripe_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="цена"),
        ),
    ]
