# Generated by Django 6.0.1 on 2026-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="название")),
                (
                    "preview",
                    models.ImageField(upload_to="course/", verbose_name="Превью"),
                ),
                ("description", models.TextField(verbose_name="описание")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "preview",
                    models.ImageField(upload_to="lesson/", verbose_name="превью"),
                ),
                ("link", models.CharField(max_length=300, verbose_name="ссылка")),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["title"],
            },
        ),
    ]
