# Generated by Django 6.0.1 on 2026-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="course/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="lesson/", verbose_name="превью"
            ),
        ),
    ]
