# Generated by Django 6.0.2 on 2026-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_alter_course_preview_alter_lesson_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=0, verbose_name="цена"),
        ),
    ]
